-- Show complete data from database
SELECT * FROM sales;

-- Show limited data
SELECT * FROM sales LIMIT 10;

-- Show limited data from specific columns
SELECT coffee_name FROM sales LIMIT 5;

-- Show distinct data
SELECT DISTINCT coffee_name FROM sales;

-- Show data count
SELECT COUNT(*) FROM sales;

-- Show data with specific condition
SELECT * FROM sales
WHERE cash_type = 'card';

-- Show data with multiple conditions
SELECT * FROM sales
WHERE coffee_name IN ('Espresso', 'Latte');

-- Show data with sorting
SELECT * FROM sales
ORDER BY coffee_name, time_of_day, weekday, month_name, monthsort; 

-- Find total revenue generated
SELECT SUM(money) AS TOTAL FROM sales;

-- Find total sales for each coffee
SELECT coffee_name, SUM(money) AS total_sales
FROM sales
GROUP BY coffee_name
ORDER BY total_sales DESC;

-- Find average transaction
SELECT AVG(money) AS avg_transaction FROM sales;

-- Find total revenue generated by each cash type
SELECT cash_type, SUM(money) AS total_revenue
FROM sales
GROUP BY cash_type;

-- Find total revenue generated by each weekday
SELECT weekday, COUNT(*) AS total_revenue
FROM sales
GROUP BY weekday
ORDER BY total_revenue DESC;

-- Find total revenue generated by each time of day
SELECT time_of_day, SUM(money) AS total_revenue
FROM sales 
GROUP BY time_of_day;


-- Find top 3 hours with highest revenue
SELECT hour_of_day, SUM(money) AS total_revenue
FROM sales 
GROUP BY hour_of_day
ORDER BY total_revenue DESC
LIMIT 3;

-- Find total revenue generated by each month
SELECT month_name, SUM(money) AS total_revenue
FROM sales 
GROUP BY month_name
ORDER BY total_revenue DESC;

-- Find total revenue generated by each coffee
SELECT coffee_name, SUM(money) AS total_revenue
FROM sales
GROUP BY coffee_name
ORDER BY total_revenue DESC;

-- Find top 3 hours with highest revenue
SELECT hour_of_day, SUM(money) AS revenue,
       RANK() OVER (ORDER BY SUM(money) DESC) AS rank
FROM sales
GROUP BY hour_of_day;

-- Find running total of sales by date
SELECT Date, SUM(money) AS daily_sales,
SUM(SUM(money)) OVER (ORDER BY Date) AS running_total
FROM sales
GROUP BY Date;

-- Find highest transaction for each date
SELECT Date, MAX(money) AS highest_transaction
FROM sales
GROUP BY Date;